app/grid/urls.py
"""grid url patterns"""
from django.conf.urls import url

from grid import views

from grid.views import (
        add_feature,
        add_grid,
        add_grid_package,
        add_new_grid_package,
        ajax_grid_list,
        delete_feature,
        delete_grid_package,
        edit_element,
        edit_grid,
        edit_feature,
        grid_detail,
        grids
    )

urlpatterns = [

    url(
        regex='^add/$',
        view=add_grid,
        name='add_grid',
    ),

    url(
        regex='^(?P<slug>[-\w]+)/edit/$',
        view=edit_grid,
        name='edit_grid',
    ),

    url(
        regex='^element/(?P<feature_id>\d+)/(?P<package_id>\d+)/$',
        view=edit_element,
        name='edit_element',
    ),

    url(
        regex='^feature/add/(?P<grid_slug>[a-z0-9\-\_]+)/$',
        view=add_feature,
        name='add_feature',
    ),

    url(
        regex='^feature/(?P<id>\d+)/$',
        view=edit_feature,
        name='edit_feature',
    ),

    url(
        regex='^feature/(?P<id>\d+)/delete/$',
        view=delete_feature,
        name='delete_feature',
    ),

    url(
        regex='^package/(?P<id>\d+)/delete/$',
        view=delete_grid_package,
        name='delete_grid_package',
    ),

    url(
        regex='^(?P<grid_slug>[a-z0-9\-\_]+)/package/add/$',
        view=add_grid_package,
        name='add_grid_package',
    ),

    url(
        regex='^(?P<grid_slug>[a-z0-9\-\_]+)/package/add/new$',
        view=add_new_grid_package,
        name='add_new_grid_package',
    ),

    url(
        regex='^ajax_grid_list/$',
        view=ajax_grid_list,
        name='ajax_grid_list',
    ),


    url(
        regex='^$',
        view=grids,
        name='grids',
    ),

    url(
        regex='^g/(?P<slug>[-\w]+)/$',
        view=grid_detail,
        name='grid',
    ),

    url(
        regex='^g/(?P<slug>[-\w]+)/landscape/$',
        view=views.grid_detail_landscape,
        name='grid_landscape',
    ),
    url(regex='^g/(?P<slug>[-\w]+)/timesheet/$',
        view=views.grid_timesheet,
        name='grid_timesheet'
    )
]

app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.urls.base import reverse_lazy
from django.views.generic.base import TemplateView, RedirectView

from django.contrib import admin

from core.views import StaticPageView
from package.models import TeamMembership
from profiles.views import profile_detail
from social_auth_local.views import require_email, validation_sent, merging_accounts

admin.autodiscover()

from apiv4.viewsets import router
from core.apiv1 import apiv1_gone
from homepage.views import homepage, error_404_view, error_500_view, health_check_view, SitemapView
from package.views import category, python3_list
from django.contrib.auth.views import logout as contrib_logout_view

urlpatterns = [

    url(r'^login/\{\{item\.absolute_url\}\}/', RedirectView.as_view(url="/login/github/")),
    url('^auth/', include('social_django.urls', namespace='social')),
    url(r'^auth/email/$', require_email, name='require_email'),
    url(r'^auth/email-sent/', validation_sent, name='validation_sent'),
    url(r'^auth/merging_accounts/', merging_accounts, name='merging_accounts'),
    # url('', include('social_auth.urls')),
    url(r"^$", homepage, name="home"),
    url(r"^health_check/$", health_check_view, name="health_check"),
    url(settings.ADMIN_URL_BASE, include(admin.site.urls)),
    url(r"^profiles/", include("profiles.urls")),
    url(r"^@(?P<hive_account>[-\.\w]+)", lambda request, hive_account: redirect('hive_profile_detail', hive_account, permanent=True)),
    url(r"^projects/", include("package.urls")),
    url(r"^grids/", include("grid.urls")),
    url(r"^feeds/", include("feeds.urls")),

    url(r"^categories/(?P<slug>[-\w]+)/$", category, name="category"),
    url(r"^categories/$", homepage, name="categories"),
    url(r"^python3/$", python3_list, name="py3_compat"),

    url(regex=r'^login/$', view=TemplateView.as_view(template_name='pages/login.html'), name='login',),
    url(r'^logout/$', contrib_logout_view, {'next_page': '/'}, 'logout',),

    # static pages
    url(r"^about/$", TemplateView.as_view(template_name='pages/faq.html'), name="about"),
    url(r"^terms/$", TemplateView.as_view(template_name='pages/terms.html'), name="terms"),
    url(r"^faq/$", TemplateView.as_view(template_name='pages/faq.html'), name="faq"),
    url(r"^syndication/$", TemplateView.as_view(template_name='pages/syndication.html'), name="syndication"),
    url(
        r"^contribute/$",
        StaticPageView.as_view(
            template_name='pages/contribute.html',
            context={
                "membership_in_hiveprojects": TeamMembership.objects.filter(project__name="Hive Projects"),
            },
        ),

        name="contribute"
    ),
    url(r"^help/$", TemplateView.as_view(template_name='pages/help.html'), name="help"),
    url(r"^sitemap\.xml$", SitemapView.as_view(), name="sitemap"),

    # new apps
    url(r"^search/", include("searchv2.urls")),

    # apiv2
    # url(r'^api/v2/', include('core.apiv2', namespace="apiv2")),

    # apiv3
    url(r'^api/v3/', include('apiv3.urls', namespace="apiv3")),

    # apiv4
    url(r'^api/v4/', include(router.urls, namespace='apiv4')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(
        regex=r"^api/v1/.*$",
        view=apiv1_gone,
        name="apiv1_gone",
    ),

    # url(r'^api/v1/', include('core.apiv1', namespace="apitest")),

    # reports
    # url(r'^reports/', include('reports.urls', namespace='reports')),

    url(r"^error/$", lambda request: 1/0),  # should trigger sentry
    url(r"^500/$", error_500_view),
    url(r"^404/$", error_404_view),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'homepage.views.error_500_view'
handler404 = 'homepage.views.error_404_view'
# handler403 = ''
# handler400 = ''

app/grid/models.py
from django.core.cache import cache
from django.db import models
from django.utils.translation import ugettext_lazy as _

from core.models import BaseModel
from grid.utils import make_template_fragment_key
from package.models import Project


class Grid(BaseModel):
    """Grid object, inherits form :class:`package.models.BaseModel`. Attributes:

    * :attr:`~grid.models.Grid.title` - grid title
    * :attr:`~grid.models.Grid.slug` - grid slug for SEO
    * :attr:`~grid.models.Grid.description` - description of the grid
      with line breaks and urlized links
    * :attr:`~grid.models.Grid.is_locked` - boolean field accessible
      to moderators
    * :attr:`~grid.models.Grid.packages` - many-to-many relation
      with :class:~`grid.models.GridPackage` objects
    """

    title = models.CharField(_('Title'), max_length=100)
    slug = models.SlugField(_('Slug'), help_text="Slugs will be lowercased", unique=True)
    description = models.TextField(_('Description'), blank=True, help_text="Lines are broken and urls are urlized")
    is_draft = models.BooleanField(_('Is Draft'), default=True)
    is_locked = models.BooleanField(_('Is Locked'), default=False, help_text="Moderators can lock grid access")
    packages = models.ManyToManyField(Project, through="GridPackage")
    header = models.BooleanField(_("Header tab?"), default=False, help_text="If checked then displayed on homepage header")

    def elements(self):
        elements = []
        for feature in self.feature_set.all():
            for element in feature.element_set.all():
                elements.append(element)
        return elements

    def __str__(self):
        return self.title

    @property
    def grid_packages(self):
        """ Gets all the packages and orders them for views and other things
         """
        gp = self.gridpackage_set.filter(package__is_published=True).select_related()
        grid_packages = gp.annotate(usage_count=models.Count('package__usage')).order_by('-usage_count', 'package')
        return grid_packages

    def save(self, *args, **kwargs):
        self.grid_packages  # fire the cache
        self.clear_detail_template_cache()  # Delete the template fragment cache
        super(Grid, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ("grid", [self.slug])

    def clear_detail_template_cache(self):
        key = make_template_fragment_key("detail_template_cache", [self.pk, ])
        cache.delete(key)

    class Meta:
        ordering = ['title']


class GridPackage(BaseModel):
    """Grid package.
    This model describes packages listed on one side of the grids
    and
    explicitly defines the many-to-many relationship between grids
    and the packages
    (i.e - allows any given package to be assigned to several grids at once).

    Attributes:

    * :attr:`grid` - the :class:`~grid.models.Grid` to which the package is assigned
    * :attr:`package` - the :class:`~grid.models.Package`
    """

    grid = models.ForeignKey(Grid)
    package = models.ForeignKey(Project)

    class Meta:
        verbose_name = 'Grid Package'
        verbose_name_plural = 'Grid Packages'

    def save(self, *args, **kwargs):
        self.grid.grid_packages  # fire the cache
        self.grid.clear_detail_template_cache()
        super(GridPackage, self).save(*args, **kwargs)

    def __str__(self):
        return '%s : %s' % (self.grid.slug, self.package.slug)


class Feature(BaseModel):
    """ These are the features measured against a grid.
    ``Feature`` has the following attributes:

    * :attr:`grid` - the grid to which the feature is assigned
    * :attr:`title` - name of the feature (100 chars is max)
    * :attr:`description` - plain-text description
    """

    grid = models.ForeignKey(Grid)
    title = models.CharField(_('Title'), max_length=100)
    description = models.TextField(_('Description'), blank=True)

    def save(self, *args, **kwargs):
        self.grid.grid_packages  # fire the cache
        self.grid.clear_detail_template_cache()
        super(Feature, self).save(*args, **kwargs)

    def __str__(self):
        return '%s : %s' % (self.grid.slug, self.title)

help_text = """
Linebreaks are turned into 'br' tags<br />
Urls are turned into links<br />
You can use just 'check', 'yes', 'good' to place a checkmark icon.<br />
You can use 'bad', 'negative', 'evil', 'sucks', 'no' to place a negative icon.<br />
Plus just '+' or '-' signs can be used but cap at 3 multiples to protect layout<br/>

"""


class Element(BaseModel):
    """ The individual cells on the grid.
    The ``Element`` grid attributes are:

    * :attr:`grid_package` - foreign key to :class:`~grid.models.GridPackage`
    * :attr:`feature` - foreign key to :class:`~grid.models.Feature`
    * :attr:`text` - the actual contents of the grid cell
    """

    grid_package = models.ForeignKey(GridPackage)
    feature = models.ForeignKey(Feature)
    text = models.TextField(_('text'), blank=True, help_text=help_text)

    class Meta:

        ordering = ["-id"]

    def save(self, *args, **kwargs):
        self.feature.save()  # fire grid_packages cache
        super(Element, self).save(*args, **kwargs)

    def __str__(self):
        return '%s : %s : %s' % (self.grid_package.grid.slug, self.grid_package.package.slug, self.feature.title)

app/grid/forms.py
"""Forms for the :mod:`grid` app
"""

from django.forms import ModelForm

from grid.models import  Element, Feature, Grid, GridPackage


class GridForm(ModelForm):
    """collects data for the new grid - a
    django ``ModelForm`` for :class:`grid.models.Grid`
    """

    def clean_slug(self):
        """returns lower-cased slug"""
        return self.cleaned_data['slug'].lower()

    class Meta:
        model = Grid
        fields = ["title", 'slug', 'description']


class ElementForm(ModelForm):
    """collects data for a new grid element -
    a ``ModelForm`` for :class:`grid.models.Element`
    """

    class Meta:
        model = Element
        fields = ['text', ]


class FeatureForm(ModelForm):
    """collects data for the feature -
    a ``ModelForm`` for :class:`grid.models.Feature`
    """

    class Meta:
        model = Feature
        fields = ['title', 'description', ]


class GridPackageForm(ModelForm):
    """collects data for a new package -
    a ``ModelForm`` for :class:`grid.models.GridPackage`
    """

    class Meta:
        model = GridPackage
        fields = ['package']

app/templates/grid/add_grid_package.html
{% extends "grid/base.html" %}

{% load i18n %}

{% block head_title %}{% blocktrans with grid.title as grid_title %}Add a package to Grid '{{ grid_title }}'{% endblocktrans %}{% endblock %}

{% block body %}

    {% url 'grid' grid.slug as grid_url %}
    <h2><a href="{% url 'home' %}">{% trans "home" %}</a> / <a href="{% url 'grids' %}">{% trans "grids" %}</a> / {% blocktrans with grid.title as grid_title %}Add a package to grid '<a href="{{ grid_url }}">{{ grid_title }}</a>'{% endblocktrans %}</h2>
        
    <form action="{{ request.PATH }}" method="post" id="grid-package-form">
        {% csrf_token %}
        <fieldset>
            <input id="search-field" type="text" name="q" value="search packages" autocomplete="off" />
            <input name="package" id="package-field" value="0" type="hidden" />
            <div id="target-parent"><div id="target"></div></div>
        
        </fieldset>

    </form>
    
    <h3>What if the Package isn't in the database?<h3>
        
    <p><a class="btn btn-default" href="{% url 'add_new_grid_package' grid.slug %}">{% trans "How about adding it? »" %}</a></p>
                


{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {          

        $('input#search-field').focus();

        var timer = null;
        $('input#search-field').keyup(function() {
            var search_text = $('input#search-field').val();
            var search_url = '{% url 'ajax_package_list' %}?q=' + search_text + '&grid={{ grid.slug }}';

            // Short delay so keystrokes don't pound search URL
            if(timer) {
                window.clearTimeout(timer);
            }

            timer = window.setTimeout(function() {
                $.get(search_url, function(data) {
                    $('#target').fadeTo('fast', 0.3, function() {
                        $('#target').html(data);
                        $('#target').fadeTo('slow', 1.0);
                    });
                });
            }, .4 * 1000);
        });

        // Ignore 'enter' key if pressed
        $("#grid-package-form").keypress(function(e) {
            if (e.which == 13) {
                return false;
            };
        });       

    });    
</script>      
{% endblock %}      

app/templates/grid/ajax_grid_list.html
{% load i18n %}
<div id="target">
    <h2>{% if grids.count %}{% trans "Grids" %}{% else %}{% trans "No grids found" %}{% endif %}</h2>
    {% if grids.count %}
        <p class="clickable">{% trans "Click a grid to add your package to it." %}</p>      
    {% endif %}
    {% for grid in grids %}
  

        <dl class="grid-item" id="grid-{{ grid.id }}">

            <dt><strong>{{ grid.title }}</strong></dt>
            <dd class="description">{{ grid.description }}</dd>        
        </dl>
    {% endfor %}
    <script type="text/javascript">
       
        {% for grid in grids %}
            $('#grid-{{ grid.id }}').mouseover(function() {
                $('#grid-{{ grid.id }}').addClass("clickable");
            });
            $('#grid-{{ grid.id }}').mouseout(function() {
                $('#grid-{{ grid.id }}').removeClass("clickable");
            });
            $('#grid-{{ grid.id }}').click(function() {
                $('form#find-a-grid-form').attr('action', "{% url 'add_grid_package' grid.slug %}");
                $("form#find-a-grid-form").submit();
            });
        {% endfor %}

    </script>    
</div>

app/templates/grid/base.html
{% extends "base.html" %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/grid.css" />
{% endblock %}


{% block body_class %}grid{% endblock %}

app/templates/grid/edit_element.html
{% extends "grid/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Edit Element" %}{% endblock %}

{% block body %}

    <h2>{% trans "Edit Element which is related to:" %}</h2>
    
    <p><strong>{% trans "Grid:" %} {{ grid }}</strong></p>
    <p><strong>{% trans "Package:" %} {{ package }}</strong></p>    
    <p><strong>{% trans "Feature:" %} {{ feature.title }}</strong> {{ feature.description}}</p>
    
    
    <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form|crispy }}
            <div class="form_block">        
                <input class="btn btn-default" type="submit" name="edit" value="{% trans "Edit" %}">
                <a href="{% url 'grid' grid.slug %}">{% trans "cancel" %}</a>
            </div>            
            
        </fieldset>
    </form>
    
    <p>
        
    </p>

{% endblock %}

{% block extra_body %}
<script>
    $("#id_text").focus();
</script>
{% endblock %}

app/templates/grid/grid_detail3.html
{% extends "base.html" %}

{% load i18n %}
{% load cache %}
{% load grid_tags %}
{% load package_tags %}

{% block head_title %}{{ grid.title }}{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <meta name="description" content="{{ grid.description }}" />
    <meta name="keywords" content="{{ grid.packages.all|join:',' }}" />
{% endblock %}

{% block body %}
{#    {% cache 1 html_grid_detail_outer grid.pk %}#}
    <div class="row">
        <div class="col-sm-6 col-lg-6 title-row m-title-panel">
            <h1 class="m-title-panel__title"><span class="m-title-panel__icon m-title-panel__icon--compare"></span>Compare {{ grid.title|lower }}</h1>
        </div>
    </div>

    <div class="col-sm-12">
        {% if grid_packages|length %}
        <table class="m-grid">
            <thead>
                {% include "grid/snippets/grid_row_header.html" %}
            </thead>
            <tbody>
                <tr>
                    <td>{% trans "Description" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>
                            {% with grid_package.package.description|truncatewords:20 as short %}
                                {% if grid_package.package.description|length > short|length %}
                                   {{ short|wordwrap:40|linebreaksbr|slice:"-3" }}<a href="{{ grid_package.package.get_absolute_url }}">...</a>
                                {% else %}
                                    {{ short|wordwrap:40|linebreaksbr }}
                                {% endif %}
                            {% endwith %}
                        </td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Category" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.category }}</td>
                    {% endfor %}
                </tr>
                <tr>
                    <td>{% trans "Project Website" %}</td>
                    {% for grid_package in grid_packages %}
                        <td><a href="{{ grid_package.package.url }}" target="_blank" rel="noopener noreferrer">{{ grid_package.package.url }}</a></td>
                    {% endfor %}
                </tr>
                {% comment %}
                <tr>
                    <td>{% trans "# Using This" %}</td>
                    {% for grid_package in grid_packages %}

                        <td class="usage-holder">
                            {% with grid_package.package as package %}
                                <span class="usage-count" id="usage-count-{{ package.id }}">{{ grid_package.usage_count }}</span>
                                {% usage_button %}
                            {% endwith %}
                        </td>
                    {% endfor %}
                </tr>
                {% endcomment %}
                <tr>
                    <td>{% trans "Project Status" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>
                            {{ grid_package.package.get_status_display }}
                        </td>
                    {% endfor %}
                </tr>
                {% comment %}
                <tr>
                    <td>{% trans "Last updated" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>
                        {% with last_updated=grid_package.package.last_updated %}
                            {% if last_updated %}
                               {{ last_updated|date:"DATETIME_FORMAT" }}
                            {% endif %}
                        {% endwith %}
                        </td>
                    {% endfor %}
                </tr>
                {% endcomment %}
                <tr>
                    <td>
                        <div class="m-grid__feature-title">{% trans "Code repository" %}</div>
                        <div class="m-grid__feature-description">
                            <a href="https://www.youtube.com/watch?v=1ehpgbb3XD0" target="_blank" rel="noopener noreferrer">Learn why being open-source is important</a>
                        </div>
                    </td>
                    {% for grid_package in grid_packages %}
                        <td>
                            {% if grid_package.package.repo_url %}
                                {{ "yes"|style_element|safe }}<br>
                                {{ grid_package.package.repo_url|safe|urlize }}
                            {% else %}
                                {{ "no"|style_element|safe }}<br>
                                This project is not open-source :(
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
{#                <tr>#}
{#                    <td>#}
{#                        <div class="m-grid__feature-title">{% trans "Contributors" %}</div>#}
{#                        <div class="m-grid__feature-description">#}
{#                            {{ "Volunteers which are officially not in the team, but helped because they wanted. Very often this is possible only if project is open-source."|wordwrap:60|linebreaksbr }}#}
{#                        </div>#}
{#                    </td>#}
{#                    {% for grid_package in grid_packages %}#}
{#                        <td>#}
{#                            {% for contributor in package.not_team_contributors|slice:"10" %}#}
{#                                <div class="contributor">#}
{#                                    <img class="img-circle" src="{{ contributor.avatar_small }}">#}
{#                                    <a class="name" href="{{ contributor.profile_page }}">{{ contributor.name }}</a>#}
{#                                </div>#}
{#                            {% endfor %}#}
{#                        </td>#}
{#                    {% endfor %}#}
{#                </tr>#}
                <tr>
                    <td>
                        <div class="m-grid__feature-title">{% trans "Development" %}</div>
                        <div class="m-grid__feature-description">Graph which illustrate rate of development</div>
                    </td>
                    {% for grid_package in grid_packages %}
                        <td>
                            {% if grid_package.package.repo_url %}
                                <img class="package-githubcommits" style="padding: 7px 0"
                                     src="https://chart.googleapis.com/chart?cht=bvg&chs=105x20&chd=t:{{ grid_package.package|commits_over_52 }}&chco=666666&chbh=1,1,1&chds=0,20"
                                />
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
                {% comment %}
                <tr>
                    <td>{% trans "Stars" %}</td>
                    {% for grid_package in grid_packages %}
                        <td>{{ grid_package.package.repo_watchers|default:"n/a" }}</td>
                    {% endfor %}
                </tr>
                {% endcomment %}
{#                <tr>#}
{#                    <td>{% trans "Participants" %}</td>#}
{#                    {% for grid_package in grid_packages %}#}
{#                        <td>#}
{#                            {% for collaborator in grid_package.package.participant_list %}#}
{#                                {% if forloop.counter <= 10 %}#}
{#                                    <a href="{{ grid_package.package.repo.url }}/{{ collaborator }}">{{ collaborator }}</a>#}
{#                                    {% if not forloop.last %}#}
{#                                        <br />#}
{#                                    {% endif %}#}
{#                                {% endif %}#}
{#                                {% if forloop.counter == 11 %}#}
{#                                    <a href="{% url 'package' grid_package.package.slug %}">{% trans "more..." %}</a>#}
{#                                {% endif %}#}
{#                            {% endfor %}#}
{#                        </td>#}
{#                    {% endfor %}#}
{#                </tr>#}

                {% for feature in features %}
                    <tr class="{% cycle 'even' 'odd' %}">
                        <td>
                            <div class="m-grid__feature-title">{{ feature.title }}</div>
                            <div class="m-grid__feature-description">{{ feature.description|wordwrap:50|linebreaksbr }}</div>
                        </td>
                        {% for grid_package in grid_packages %}
                            {% with elements|hash:feature.pk|hash:grid_package.pk as element %}

                            <td id="element-f{{ feature.pk }}-p{{ grid_package.pk }}">
                                {{ element.text|style_element|safe|urlize|linebreaksbr }}
                            </td>

                            {% endwith %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    {% else %}
        {% if request.user.is_authenticated and profile.can_add_grid_package %}
        <p><a href="{% url 'add_grid_package' grid.slug %}"><span class="glyphicon glyphicon-plus"></span>&nbsp;{% trans "Add a package to get a grid view" %}</a></p>
        {% endif %}
    {% endif %}

    </div>
{#    {% endcache %}#}
{% endblock %}

app/templates/grid/grid_timesheet.html
{% extends "grid/base.html" %}

{% load i18n %}


{% block head_title %}Timesheet for {{ grid.title }}{% endblock %}

{% block extra_head %}
 <link href="{{ STATIC_URL }}css/timesheet.css" media="all" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>{% trans "Grid Time Table" %}</h2>
        <div id="timesheet"></div>
    </div>
  </div>
</div>

{% endblock %}
{% if not forloop.last %},{% endif %}
{% block extra_body %}
    <script src="{{ STATIC_URL }}js/timesheet.js" type="text/javascript"></script>
    <script type="text/javascript">
        new Timesheet('timesheet', 2008, 2016, [
        {% for grid_package in grid_packages %}
            {% with grid_package.package as package %}
            ['{{ package.created|date:"m/Y" }}', '{{ package.last_commit.commit_date|date:"m/Y" }}', '{{ package.slug }}', ''],
            {% endwith %}
        {% endfor %}
        ]);


    </script>
{% endblock %}

app/templates/grid/grids.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Grids" %}{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>{% trans "Grids" %}</h2>
      {% if request.user.is_authenticated and profile.can_add_grid %}
        <p>
          <a class="btn btn-default" href="{% url 'add_grid' %}">{% trans "add grid »" %}</a>
        </p>
      {% endif %}
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-12">
      <table class="table">
        <thead>
          <tr>
            <th>{% trans "Grid" %}</th>
            <th>{% trans "Description" %}</th>
            <th>{% trans "Last Modified" %}</th>
            <th>{% trans "Packages" %}</th>
            <th>{% trans "Features" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for grid in grids %}
            <tr>
              <td><a href="{% url 'grid' grid.slug %}">{{ grid.title }}</a></td>
              <td>{{ grid.description }}</td>
              <td>{{ grid.modified|date:"D d M" }}</td>
              <td>{{ grid.gridpackage_count }}</td>
              <td>{{ grid.feature_set.count }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>
{% endblock %}

app/templates/grid/update_feature.html
{% extends "grid/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      
      <h2>{% trans "Grid Feature" %}</h2>

      <p>{% trans "Add/edit a feature of the" %} <a href="{% url 'grid' grid.slug %}">{{ grid.title }}</a> {% trans "grid." %}</p>
      
      <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
          {{ form|crispy }}
          <div class="form_block">
            <input class="btn btn-default" type="submit" name="edit" value="Edit">
          </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_body %}
<script>
    $("#id_title").focus();
</script>
{% endblock %}

app/templates/grid/update_grid.html
{% extends "grid/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>{% trans "Grid Form" %}</h2>
    
      <p>{% trans "Grids added here are publicly listed in the" %} <a href="/grids">{% trans "list of all grids" %}</a>.</p>
      <p>{% trans "Periodically, Daniel and Audrey will add some of these grids to the top navigation bar!" %}</p>
    
      <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <fieldset>
          {{ form|crispy }}
          <div class="form_block">
            <input class="btn btn-default" type="submit" name="add" value="{% trans "Submit »" %}">
          </div>            
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
    $(function() {          
        $('input#id_title').focus();
        
    });    
</script>      
{% endblock %}      
        